# -*- coding: utf-8 -*-
"""juridicator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LDYf4wfXuVKLAtGtw7TyEACsn7ZEH5Ew
"""

#Olá, esse é o Juridicator,para utilizar o programa clique no botão de play ao lado e responda as 3 perguntas que aparecerão.
#Nas perguntas de condição e julgamento, responda somente usando Sim ou Não.
#O programa só funciona uma vez por clique, toda vez que vc responder as 3 questões o programa te dará um resultado.
#Para usar de novo , é so clicar novamente no play 
acusacao = str(input("Qual é a acusação:"))
acusado = str(input("Quem cometeu ?:"))
condicao = str(input("A acusação é verdadeira ?"))
julgamento = str(input("Foi julgado ainda ?"))
if condicao == "Sim" and julgamento == "Sim":
   print("Foi julgado pelo tribunal responsável,que {} cometeu {}".format(acusado,acusacao))
elif condicao == "Sim" and julgamento == "Não":
  print("Têm se dito que {} cometeu o crime de {},porém deve se aguardar até que o acusado tenha sido julgado em todas as intâncias.".format(acusado,acusacao))
elif condicao == "Não" and julgamento == "Não":
  print("Ainda não foi investigado se {} tenha cometido o crime de {}".format(acusado,acusacao))
elif condicao == "Não" and julgamento == "Sim":
  print("{} foi investigado por ter cometido o crime de {},porém foi descoberto que ele não cometeu o crime o qual foi acusado".format(acusado,acusacao))